### ISSUE TITLE
class 9 mapping for apollo dataset?

### ISSUE THREAD

**Issue by georgosgeorgos** [ucbdrive/bdd-data#1]
Hi,

How do you map the CityScapes class 9 (terrain) in the Apollo dataset?
There is no 9 [here](https://github.com/ucbdrive/bdd-data/blob/master/doc/apollo/apollo_train_id.csv)

**Comment by fyu** [comment]
Because terrain is not labeled in Apollo.

**Comment by georgosgeorgos** [comment]
quite a good reason.
