### ISSUE TITLE
How to evaluate my model

### ISSUE THREAD

**Issue by Programmerwyl** [ucbdrive/bdd-data#14]
If I use tensorflow to train bdd100k, then I get  .ckpt file ,how to use evaluate.py file to evaluate my model
The 'evaluate.py' file has not interface to use the generation for training .

**Comment by fyu** [comment]
You have to convert the results to evaluation format: https://github.com/ucbdrive/bdd-data/blob/master/doc/evaluation.md#

**Comment by BernardinD** [comment]
@fyu So we simply change the APIoU?
