### ISSUE TITLE
When I run show_labels.py where occurs "module 'bdd_data.show_labels' has no attribute '__path__')"

### ISSUE THREAD

**Issue by kinredon** [ucbdrive/bdd-data#17]
I have run:

`python3 -m bdd_data.show_labels.py --image-dir 
bdd100k/images/100k/train -l bdd100k/labels/bdd100k_labels_images_train.json`

in terminal. 
but then it occurs:

`Error while finding module specification for 'bdd_data.show_labels.py' (AttributeError: module 'bdd_data.show_labels' has no attribute '__path__')
`

I cannot locate this error , so how can I fix it?

OS: MAC OS

thank you!

**Comment by kinredon** [comment]
I have solved this problem by modify the common:

`python3 -m bdd_data.show_labels.py --image-dir bdd100k/images/100k/train -l bdd100k/labels/bdd100k_labels_images_train.json`

to 

`python3 show_labels.py --image-dir bdd100k/images/100k/train -l bdd100k/labels/bdd100k_labels_images_train.json`

it run successfully. then it still occurs an error:

`ModuleNotFoundError: No module named '__main__.label'; '__main__' is not a package`

here has a solution: https://github.com/ucbdrive/bdd-data/issues/5

**Comment by huangyuyao** [comment]
Write `python3 -m bdd_data.show_labels`  instead of `python3 -m bdd_data.show_labels.py` should do the trick.

**Comment by karolmajek** [comment]
this should be changed in Readme...
