### ISSUE TITLE
How to download dataset via wget?

### ISSUE THREAD

**Issue by kinredon** [ucbdrive/bdd-data#18]
I cannot find the dataset url, so how to download dataset via wget or other command?

**Comment by fyu** [comment]
Most of the downloading links require a login session and it is hard to download with the command line.

**Comment by vincentschen** [comment]
Are there plans to support command line download? Downloading via browser is tricky on clusters without GUIs.

**Comment by saravanabalagi** [comment]
Why is this issue closed? Is there a solution to the problem already?

**Comment by deepakksingh** [comment]
I agree with @vincentschen.
@fyu Could you kindly help us out here for the downloading part.
Thank you.
