### ISSUE TITLE
Dataset video download split

### ISSUE THREAD

**Issue by zhanghanduo** [ucbdrive/bdd-data#2]
The video for download is 1.8 TB (I don't have such big drive size ::>_<:: ). So I wanna ask can you split the dataset into pieces (maybe also offer p2p download entry)?
Actually not everyone needs all the videos for research. So it is better you could provide video segments. Thank you!

**Comment by fyu** [comment]
I am working on this issue to provide more options to download the videos.

**Comment by zhanghanduo** [comment]
Thanks for the reply! Now I feel relieved~

**Comment by isht8** [comment]
@fyu Is there some time line by which I can expect the video splits? Thanks
