### ISSUE TITLE
Inconsistency between label format in format.md and actual labels

### ISSUE THREAD

**Issue by maaland** [ucbdrive/bdd-data#22]
Hi

Unless I'm misunderstanding something there seems to be an inconsistency between the label format described in the `format.md` file, and the actual labels found in `bdd100k_labels_images_val.json`  and `bdd100k_labels_images_train.json`

For instance, in the actual `json` files we find fields like `labels.manualAttributes` and `labels.manualShape` but these are not explicitly mentioned in the description. But perhaps the `labels.manual` field is meant to describe them?

As a second example, the description contains fields like `intrinsics` and `extrinsics` which are not found in the `json` files. 

If this is in fact an error I would be happy to create a PR to make the description in the `format.md` file consistent with the actual `json` files.

Thanks

**Comment by fyu** [comment]
Thanks for raising the issue. I updated the format and its description just now to avoid similar confusion. https://github.com/ucbdrive/bdd-data/commit/c00e08eb2773404d03b960a58b6abbc08696cb5f

**Comment by maaland** [comment]
I appreciate the quick response, thanks!

**Comment by phongnhhn92** [comment]
Hello guys, I know you guy close this issue but I can not find intrinsics and extrinsics in both json files. Is this possible to get intrinsics and extrinsics information for each frames ?

**Comment by vjg28** [comment]
Hi, 
I have the same question. I checked for intrinsics and extrinsics in all label files, but didn't found any! Is there any updated dataset link where the data after 08-28-2018 is available?
Thanks
