### ISSUE TITLE
evaluate code mistake

### ISSUE THREAD

**Issue by weitaoatvison** [ucbdrive/bdd-data#3]
I have submit the road object detection task result, but the system said it is wrong. I use your evaluate code to check the validate result and I find the code will break if the result has a record of an object but in gt there are no this class of object. 
error code is here:
gt_boxes = image_gt_boxes[p['name']]
gt_checked = image_gt_checked[p['name']]

so, I think my submission mistake may caused by this line of code.

**Comment by lbin** [comment]
@fyu

**Comment by fyu** [comment]
fixed https://github.com/ucbdrive/bdd-data/commit/2d2b0629d08b488967ba23689ffc0b7cbd75661e
